[[springintegration]]

== Spring integration
== Spring集成

While you can definitely use Flowable DMN without Spring, we've provided some very nice integration features that are explained in this chapter.

虽然我们可以在没有Spring的情况下使用 Flowable DMN，但我们还提供了一些非常好的集成特性，本章我们将对此进行说明。

=== DmnEngineFactoryBean

=== DMN引擎接口

The +DmnEngine+ can be configured as a regular Spring bean. The starting point of the integration is the class +org.flowable.dmn.spring.DmnEngineFactoryBean+. This bean takes a DMN engine configuration and creates the DMN engine.  This means that the creation and configuration of properties for Spring is the same as documented in the <<configuration,configuration section>>. For Spring integration, the configuration and engine beans will look like this:

我们可以将++DMN引擎++配置为普通的Spring Bean。配置的入口是++org.flowable.dmn.spring.DmnEngineFactoryBean++类。这个bean采用DMN引擎配置同时创建DMN引擎。 这意味着Spring属性的创建和配置与<<configuration,configuration章节>>中记录的是一致的。Spring集成所用的配置与引擎Bean如下所示：

[source,xml,linenums]
----
<bean id="dmnEngineConfiguration" class="org.flowable.dmn.spring.SpringDmnEngineConfiguration">
    ...
</bean>

<bean id="dmnEngine" class="org.flowable.dmn.spring.DmnEngineFactoryBean">
  <property name="dmnEngineConfiguration" ref="dmnEngineConfiguration" />
</bean>

----

Note that the +dmnEngineConfiguration+ bean now uses the +org.flowable.dmn.spring.SpringDmnEngineConfiguration+ class.

注意：DmnEngine Bean的配置现在使用的是++org.flowable.dmn.spring.SpringDmnEngineConfiguration++类。


=== Automatic resource deployment

=== 自动资源部署

Spring integration also has a special feature for deploying resources.  In the DMN engine configuration, you can specify a set of resources. When the DMN engine is created, all these resources will be scanned and deployed.  There is filtering in place that prevents duplicate deployments.  Only when the resources have actually changed will new deployments be deployed to the Flowable DMN DB. This makes sense in a lot of use case, where the Spring container is rebooted often (for example, testing).

Spring集成还有一个部署资源的特殊功能。在DMN引擎配置中，我们可以指定一组资源。一旦创建DMN引擎，所有这些资源都会被扫描和部署。适当的过滤可以防止重复的部署。只有当资源确实发生变化时，才会重新部署至Flowable DMN数据库中。这在Spring容器经常重启（例如：测试）的时候非常有用。

Here's an example:

以下是一个例子：

[source,xml,linenums]
----
<bean id="dmnEngineConfiguration" class="org.flowable.spring.SpringDmnEngineConfiguration">
  ...
  <property name="deploymentResources"
    value="classpath*:/org/flowable/spring/test/autodeployment/autodeploy/decision*.dmn" />
</bean>

<bean id="dmnEngine" class="org.flowable.dmn.spring.DmnEngineFactoryBean">
  <property name="dmnEngineConfiguration" ref="dmnEngineConfiguration" />
</bean>
----

By default, the configuration above will group all of the resources matching the filtering into a single deployment to the Flowable DMN engine. The duplicate filtering to prevent re-deployment of unchanged resources applies to the whole deployment. In some cases, this may not be what you want. For instance, if you deploy a set of DMN resources this way, and only a single
 DMN definition in those resources has changed, the deployment as a whole will be considered new and all of the process definitions in that deployment will be re-deployed, resulting in new versions of each of the DMN definitions, even though only one was actually changed.

默认情况下，上面的配置方式会将符合这个过滤器的所有资源组织在一起，作为Flowable DMN引擎的一个部署。为避免未改变资源的重复部署，重复检测过滤将作用于整个部署。有时候，这并不是你想要的。例如，如果我们以这种方式部署了一组DMN资源，即使这些资源中只有的一个DMN流程定义发生了改变，整个部署都被视为新部署，这个部署中的所有流程定义都将被重新部署，这将导致每个流程定义都会刷新版本，即使实际上只有一个流程定义发生了变化。

To be able to customize the way deployments are determined, you can specify an additional property in the +SpringDmnEngineConfiguration+, +deploymentMode+. This property defines the way deployments will be determined from the set of resources that match the filter. There are three values that are supported by default for this property:

要想定制部署的方式，我们可以在++SpringProcessEngineConfiguration++中指定一个额外属性++deploymentMode++，这个属性定义了部署一组符合过滤器的资源的方式。这个属性默认支持3个值：

* ++default++: Group all resources into a single deployment and apply duplicate filtering to that deployment. This is the default value and it will be used if you don't specify a value.

* ++default++: 将所有资源组织在一个部署中，整体用于重复检测过滤。这是默认值，在不指定属性值的时候也会用这个值。

* ++single-resource++: Create a separate deployment for each individual resource and apply duplicate filtering to that deployment. This is the value you would use to have each DMN definition be deployed separately and only create a new DMN definition version if it has changed.

* ++single-resource++: 为每个资源创建一个单独的部署，并用于重复检测过滤。如果希望单独部署每一个DMN流程定义，并且只有在它发生变化时才创建新的DMN流程定义版本，就应该使用这个值。

* ++resource-parent-folder++: Create a separate deployment for resources that share the same parent folder and apply duplicate filtering to that  deployment. This value can be used to create separate deployments for most resources, but still be able to group some by placing them in a shared folder. Here's an example of how to specify the +single-resource+ configuration for ++deploymentMode++:

* ++resource-parent-folder++: 为同一个目录下的资源创建一个单独的部署，并用于重复检测过滤。这个属性值可以为大多数资源创建独立的部署。同时仍可以通过将部分资源放在同一个目录下，将它们组织在一起。以下是一个将++deploymentMode++设置为++single-resource++的例子：

[source,xml,linenums]
----
<bean id="dmnEngineConfiguration"
    class="org.flowable.dmn.spring.SpringDmnEngineConfiguration">
  ...
  <property name="deploymentResources" value="classpath*:/flowable/*.dmn" />
  <property name="deploymentMode" value="single-resource" />
</bean>
----

In addition to using the values listed above for +deploymentMode+, you may want customized behavior towards determining deployments. If so, you can create a subclass of +SpringDmnEngineConfiguration+ and override the +getAutoDeploymentStrategy(String deploymentMode)+ method.  This method determines which deployment strategy is used for a certain value of the +deploymentMode+ configuration.

除了使用上面列出的++deploymentMode++值之外，我们还可以自定义组织部署的行为。如果是这样，我们可以创建++SpringDmnEngineConfiguration++的子类并覆盖++getAutoDeploymentStrategy(String deploymentMode)++方法。 这个方法用来确定将哪种部署策略用于++deploymentMode++属性给定的值。


[[springUnitTest]]


=== Unit testing

=== 单元测试

When integrating with Spring, decisions can be tested very easily using the standard <<apiUnitTesting,Flowable testing facilities>>.
The following examples show how a decision is tested in typical Spring-based JUnit 4 and 5 tests:

集成Spring后，我们可以很轻松使用标准的<<apiUnitTesting,Flowable测试工具>>测试业务流程。下面的例子我们来展示如何使用典型的Spring单元测试工具测试业务流程：

.JUnit 5 test
.JUnit 5 测试
[source,java,linenums]
----
@ExtendWith(FlowableDmnSpringExtension.class)
@ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = DmnSpringJunitJupiterTest.TestConfiguration.class)
public class SpringJunit4Test {

    @Autowired
    private DmnEngine dmnEngine;

    @Autowired
    private DmnRuleService ruleService;

    @Test
    @DmnDeploymentAnnotation
    public void simpleDecisionTest() {
        Map<String, Object> executionResult = ruleService.createExecuteDecisionBuilder()
            .decisionKey("extensionUsage")
            .variable("inputVariable1", 2)
            .variable("inputVariable2", "test2")
            .executeWithSingleResult();

        Assertions.assertThat(executionResult).containsEntry("output1", "test1");
    }
}
----

.JUnit 4 test
.JUnit 4 测试
[source,java,linenums]
----
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration("classpath:org/flowable/spring/test/junit4/springTypicalUsageTest-context.xml")
public class SpringJunit4Test {

    @Autowired
    private DmnEngine dmnEngine;

    @Autowired
    private DmnRuleService ruleService;

    @Autowired
    @Rule
    public FlowableDmnRule flowableSpringRule;

    @Test
    @DmnDeploymentAnnotation
    public void simpleDecisionTest() {
        Map<String, Object> executionResult = ruleService.createExecuteDecisionBuilder()
                .decisionKey("extensionUsage")
                .variable("inputVariable1", 2)
                .variable("inputVariable2", "test2")
                .executeWithSingleResult();

        Assertions.assertThat(executionResult).containsEntry("output1", "test1");
    }
}
----

Note that for this to work, you need to define an _org.flowable.dmn.engine.test.FlowableDmnRule_ bean in the Spring configuration (which is injected by auto-wiring in the example above).

注意：这个例子正常运行的条件是，需要在Spring配置中定义一个 _org.flowable.dmn.engine.test.FlowableDmnRule_ Bean（在上面的例子中通过@Autowire自动注入）

[source,xml,linenums]
----
<bean id="flowableDmnRule" class="org.flowable.dmn.engine.test.FlowableDmnRule">
    <property name="dmnEngine" ref="dmnEngine"/>
</bean>

----
