[[chDeployment]]

== Deployment
部署

=== External resources

外部资源

Case definitions live in the Flowable database. These case definitions can reference delegation classes when using Service Tasks or Spring beans from the Flowable configuration file. These classes and the Spring configuration file have to be available to all CMMN engines that may execute the case definitions.

案例定义位于Flowable 数据库中。当在Flowable 配置文件使用Service Tasks或Spring Beans时，这些案例定义可以引用委托类来处理。
这些类和Spring配置文件,必须可以用于所有可能执行案例定义的CMMN引擎。

==== Java classes

JAVA 类

All custom classes that are used in your case definition (for example, PlanItemJavaDelegates used in Service Tasks) should be present on the engine's classpath when an instance of the case is started.

在案例定义中使用的所有自定义类（例如，服务任务中使用的PlanItemJavaDelegates）都应该在启动案例实例时，配置在引擎的类路径上。

During deployment of a case definition however, those classes don't have to be present on the classpath. This means that your delegation classes don't have to be on the classpath when deploying a new case definition, for example.
When you are using the demo setup and you want to add your custom classes, you should add a JAR containing your classes to the flowable-task or flowable-rest webapp lib. Don't forget to include the dependencies of your custom classes (if any) as well. Alternatively, you can include your dependencies in the libraries directory of your Tomcat installation, +${tomcat.home}/lib+ (or similar place for other web containers).

但是，在部署案例定义期间，这些类不必配置在类路径上。也就是说在部署新的案例定义时，您的委托类不必位于类路径上，例如：当您使用演示安装程序并要添加自定义类时，应该将包含类的JAR添加到“flowable-task”或“flowable-rest” webapp lib中。别忘了还要包括自定义类（如果有的话）的依赖项。或者您也可以将依赖项配置在Tomcat安装的libraries目录中，$tomcat.home/lib（或其他Web容器的类似位置）。

==== Using Spring beans from a case instance

从实例中使用SpringBeans

When expressions or scripts use Spring beans, those beans have to be available to the engine when executing the case definition. If you are building your own webapp and you configure your CMMN engine in your context as described in <<springintegration,the spring integration section>>, that is straightforward. But bear in mind that you also should update the Flowable task and rest webapps with that context if you use it.

当在表达式或脚本使用SpringBean时，在执行案例定义时，这些bean必须对引擎可用。如果您正在构建自己的webapp，并按照《Spring集成章节》中的相关章节描述，在您的应用上下问文中配置CMMN引擎，那这很简单。但请记住，如果您使用"Flowable task"和"Flowable rest" webapps，那么也应该使用该上下文对其进行更新。

[[versioningOfCaseDefinitions]]


=== Versioning of case definitions

案例定义的版本管理

CMMN doesn't have a notion of versioning.  That is actually good, because the executable CMMN file will probably live in a version control system repository (such as Subversion, Git or Mercurial) as part of your development project.  However, versions of case definitions are created in the engine as part of deployment. During deployment, Flowable will assign a version to the +CaseDefinition+ before it is stored in the Flowable DB.

For each case definition in a deployment, the following steps are performed to initialize the properties +key+, +version+, +name+ and ++id++:

* The case definition +id+ attribute in the XML file is used as the case definition +key+ property.
* The case definition +name+ attribute in the XML file is used as the case definition +name+ property. If the name attribute is not specified, then the id attribute is used as the name.
* The first time a case with a particular key is deployed, version 1 is assigned.  For all subsequent deployments of case definitions with the same key, the version will be set 1 higher than the highest currently deployed version. The key property is used to distinguish case definitions.

CMMN没有版本控制的概念，这实际上很好，因为可执行CMMN文件可能作为开发项目的一部分存在于版本控制系统库中（如Subversion、Git或Mercurial）。但是，案例定义的版本是作为部署的一部分在引擎中创建的。在部署过程中，flowable将为CaseDefinition分配一个版本，然后将其存储在flowable数据库中



Take for example the following case

以下面的例子为例

[source,xml,linenums]
----
<definitions id="myDefinitions" >
  <case id="myCase" name="My important case" >
    ...
----

When deploying this case definition, the case definition in the database will look like this:

部署此案例定义时，数据库中的案例定义将看起来像这样

[options="header"]
|===============
|id|key|name|version
|676|myCase|My important case|1

|===============

Suppose we now deploy an updated version of the same case (for example, changing some human tasks), but the ++id++ of the case definition remains the same. The case definition table will now contain the following entries:

假设我们现在部署相同案例的更新版本（例如，更改一些人工任务），但案例定义的ID保持不变。案例定义表现在将包含以下条目：

[options="header"]
|===============
|id|key|name|version
|676|myCase|My important case|1
|870|myCase|My important case|2

|===============

When the ++runtimeService.createCaseInstanceBuilder().caseDefinitionKey("myCase").start()++ is called, it will now use the case definition with version ++2++, as this is the latest version of the case definition.

当调用RuntimeService.CreateCaseInstanceBuilder（）.CaseDefinitionKey（“MyCase”）.Start（）时，它现在将在版本2中使用案例定义，因为这是案例定义的最新版本。

Should we create a second case, as defined below and deploy this to Flowable, a third row will be added to the table.

如果我们像下面定义的那样创建第二个案例并将其部署到Flowable，那么第三行将添加到表中。


[source,xml,linenums]
----
<definitions id="myNewDefinitions" >
  <case id="myNewCase" name="My important case" >
    ...
----

The table will look like this:

这个表看起来像这样：

[options="header"]
|===============
|id|key|name|version
|676|myCase|My important case|1
|870|myCase|My important case|2
|1033|myNewCase|My important case|1

|===============

Note how the key for the new case is different from our first case. Even though the name is the same (we should probably have changed that too), Flowable only considers the +id+ attribute when distinguishing cases. The new case is therefore deployed with version 1.

请注意：新案例的关键与第一个案例有何不同？尽管名称是相同的（我们可能也应该更改它），但在区分大小写时，Flowable只考虑ID属性。因此，新案例会与版本1一起部署。

[[deploymentCategory]]


=== Category

类别

Both deployments and case definitions have user-defined categories.  The case definition category is initialized with the value of the targetNamespace attribute in the CMMN XML: +<definitions ... targetNamespace="yourCategory" ...+

部署和案例定义都有用户定义的类别。案例定义类别是用CMMN XML中的“targetNamespace”属性的值初始化的：<definitions…targetNamespace=“您定义的类别”…

The deployment category can also be specified in the API like this:

部署类别也可以在API中指定，如下所示：

[source,java,linenums]
----
repositoryService
    .createDeployment()
    .category("yourCategory")
    ...
    .deploy();
----
